# Generated by Django 2.0.3 on 2018-04-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('event_title', models.CharField(max_length=60, verbose_name='event_title')),
                ('event_description', models.CharField(max_length=250, verbose_name='event_description')),
                ('event_image', models.CharField(max_length=2000, verbose_name='event_image_url')),
                ('event_choice_1', models.CharField(max_length=500, verbose_name='event_choice_1')),
                ('event_choice_2', models.CharField(max_length=500, verbose_name='event_choice_2')),
            ],
        ),
    ]
